# Generated by Django 5.2.4 on 2026-05-01 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_order_is_paid_order_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('accessory', 'Accessory')], default='mobile', max_length=20),
        ),
    ]
