# Generated by Django 5.2.4 on 2026-05-27 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='display_number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
